sudo: required
dist: trusty
language: scala
scala:
  - 2.11.8
branches:
  only:
    - master
script:
 # - ${TRAVIS_BUILD_DIR}/runAllTests.sh
  - sbt test
  - sbt main/test
  - sbt causalAssembly/test
  - sbt export/test
